GET http://localhost:3000/api/animales HTTP/1.1

###

GET http://localhost:3000/api/animales/3 HTTP/1.1

###

POST http://localhost:3000/api/animales HTTP/1.1
content-type: application/json

{
    "nombre": "Pez Payazo",
    "tipo": "Pez"
}

###

PUT http://localhost:3000/api/animales/3 HTTP/1.1
content-type: application/json

{
    "nombre": "Guacamaya",
    "tipo": "Ave"
}

### 

DELETE http://localhost:3000/api/animales/2 HTTP/1.1
content-type: application/json
