GET http://localhost:3000/api/animales HTTP/1.1

###

GET http://localhost:3000/api/animales/1 HTTP/1.1

###

POST http://localhost:3000/api/animales HTTP/1.1
content-type: application/jsons

{
    "nombre": "Hormiga",
    "tipo": "Insecto"
}

###

PUT http://localhost:3000/api/animales/4 HTTP/1.1
content-type: application/json

{
    "nombre": "Mono",
    "tipo": "Mamifero"
}

### 

DELETE http://localhost:3000/api/animales/2 HTTP/1.1
content-type: application/json
